# Generated by Django 4.2.29 on 2026-04-19 00:40

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_country_remove_location_country_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('₦', 'Nigerian Naira'), ('$', 'US Dollar'), ('£', 'British Pound'), ('€', 'Euro')], default='₦', max_length=10)),
                ('status', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=10)),
                ('type', models.CharField(max_length=100)),
                ('area', models.IntegerField(blank=True, help_text='Area in square meters', null=True)),
                ('guests', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('bedrooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('living_rooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('garages', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('units', models.IntegerField(blank=True, help_text='Number of similar units available', null=True)),
                ('description', models.TextField()),
                ('amenities', models.JSONField(default=list, help_text='List of amenities')),
                ('entity', models.CharField(blank=True, help_text='Property owner/manager entity', max_length=255, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='api.agent')),
                ('location_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='api.location')),
            ],
            options={
                'verbose_name_plural': 'Apartments',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('category', models.CharField(blank=True, help_text='e.g., Living Room, Kitchen, Bedroom, Bathroom', max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_primary', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.apartment')),
            ],
            options={
                'ordering': ['order', '-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='api.apartment')),
            ],
            options={
                'verbose_name_plural': 'Property Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.apartment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_assignments', to='api.inventoryitem')),
            ],
            options={
                'verbose_name_plural': 'Apartment Inventory',
                'ordering': ['apartment', 'item'],
                'unique_together': {('apartment', 'item')},
            },
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order', '-is_primary']},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='blockeddate',
            name='property',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garages',
        ),
        migrations.RemoveField(
            model_name='property',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='property',
            name='living_rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='units',
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='entity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Exterior, Interior, Amenities, Construction', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PropertyInquiry',
        ),
        migrations.AddField(
            model_name='apartment',
            name='parent_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='api.property'),
        ),
        migrations.AlterUniqueTogether(
            name='externalcalendar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='api.apartment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.apartment'),
        ),
        migrations.AddField(
            model_name='externalcalendar',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_calendars', to='api.apartment'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='api.apartment'),
        ),
        migrations.AlterUniqueTogether(
            name='externalcalendar',
            unique_together={('apartment', 'source')},
        ),
        migrations.RemoveField(
            model_name='externalcalendar',
            name='property',
        ),
    ]
