# Generated by Django 4.2.29 on 2026-04-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apartment_apartmentimage_apartmentinquiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='location_data',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='location_data',
            new_name='location',
        ),
    ]
