# Generated by Django 4.2.29 on 2026-06-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_walk_in_booking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
