# Generated by Django 4.2.29 on 2026-06-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_id_type_to_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='house_rules',
            field=models.TextField(blank=True, help_text='House rules shown on receipt', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('pos', 'POS Terminal')], default='paystack', max_length=50),
        ),
    ]
