# Generated by Django 4.2.29 on 2026-06-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_apartment_parking_lock_booking_email_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-featured', 'title'], 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
