# Generated by Django 4.2.29 on 2026-05-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_inventoryitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_slug', models.SlugField(help_text='Slug of the Django Ledger EntityModel', max_length=200)),
                ('main_ledger_xid', models.SlugField(default='booking-revenue', help_text='ledger_xid of the main booking revenue ledger', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ledger Setup',
                'verbose_name_plural': 'Ledger Setup',
            },
        ),
        migrations.CreateModel(
            name='PaymentLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_entry_uuid', models.UUIDField(help_text='UUID of the JournalEntryModel in Django Ledger')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='api.payment')),
            ],
            options={
                'verbose_name': 'Payment Ledger Entry',
                'verbose_name_plural': 'Payment Ledger Entries',
            },
        ),
    ]
